apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-travel
  namespace: travel-micro
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: microservice-travel
  template:
    metadata:
      labels:
        app: microservice-travel
        version: v3
    spec:
      containers:
        - name: travel-container
          image: localhost:5000/microservice-travel:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      volumes:
        - name: app-config
          configMap:
            name: microservice-travel-config
            defaultMode: 420