apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: travel-micro
generatorOptions:
  disableNameSuffixHash: true
resources:
  - deployment.yaml
  - service.yaml
  - mongo-deployment.yaml
  - redis-deployment.yaml
configMapGenerator:
  - name: microservice-travel-config
    files:
      - app-config/application.yaml
